@echo off
REM pgAdmin II - PostgreSQL Tools
REM Copyright (C) 2001, The pgAdmin Development Team
REM This software is released under the pgAdmin Public Licence
REM
REM BuildAll.bat - Recompile all pgAdmin II Code
REM Note that this doesn't rebuild the documentation

echo Creating clsPgApp.cls class...
cscript //nologo pgadmin2\crtpgAppClass.vbs > pgadmin2\clspgApp.cls

cd pgschema
echo Building pgSchema...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make pgSchema.vbp /outdir ..\binaries

cd ..\pgadmin2
echo Building Abstract Exporter...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Exporters\Abstract\pgAbsExp.vbp /outdir ..\binaries
echo Building Access Exporter...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Exporters\Access\pgAccess.vbp /outdir ..\binaries
echo Building ASCII Exporter...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Exporters\ASCII\pgASCII.vbp /outdir ..\binaries
echo Building Excel Exporter...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Exporters\Excel\pgExcel.vbp /outdir ..\binaries
echo Building HTML Exporter...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Exporters\HTML\pgHTML.vbp /outdir ..\binaries

echo Building Abstract Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\Abstract\pgAbsPlg.vbp /outdir ..\binaries
echo Building hba.conf Editor Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\hba\pgHba.vbp /outdir ..\binaries
echo Building MSysConf Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\MSysConf\pgMSysConf.vbp /outdir ..\binaries
echo Building Security Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\Security\pgSecurity.vbp /outdir ..\binaries
echo Building Import Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\Import\pgImport.vbp /outdir ..\binaries
echo Building Publishing Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\Publishing\pgPublishing.vbp /outdir ..\binaries
echo Building ConnDebug Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\ConnDebug\pgConnDebug.vbp /outdir ..\binaries
echo Building Migration Wizard Plugin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Plugins\Migration\pgMigration.vbp /outdir ..\binaries

cd ..\ActiveX
echo Building Highlightbox...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make Highlightbox\Highlightbox.vbp /outdir ..\binaries

cd ..\pgadmin2
echo Building pgAdmin...
"%ProgramFiles%\Microsoft Visual Studio\VB98\VB6.EXE" /make pgAdmin2.vbp /outdir ..\binaries

cd ..

echo
echo Done!
